name: membership-service-dev

env:
  MODULE: membership-service
  BUILD_ID: ${{github.sha}}
  HELM_VALUE: membership-service-chart/values-dev.yaml
  HELM_BRANCH: dev


on:
  push:
    branches: [ "devops2" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          # role-to-assume: arn:aws:iam::730335207750:role/my-github-actions-role
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} # optional
          # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-eks-practice
          IMAGE_TAG: ${{ env.BUILD_ID }}
        run: |
          envsubst < Dockerfile.light-template | docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f - .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


      - name: Checkout Helm Repository
        uses: actions/checkout@v3
        with:
          repository: KIYOUNGYI/my-eks-practice-helm-charts
          path: helm-chart
          ref: main
          ssh-key: ${{ secrets.HELM_CHARTS_REPO_KEY }}

      - name: Change Image tag of the Helm value
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq -i '.image.tag = "${{env.BUILD_ID}}"' helm-chart/${{env.HELM_VALUE}}

      - name: Commit and Push HELM changes
        run: |
          echo "BUILD_ID: {${{env.BUILD_ID}}}"
          cd helm-chart
          git config --local user.email "yky2798@gmail.com"
          git config --local user.name "GitHubAction"
          git add .
          git commit -m "Commit HELM changes: ${{env.ECR_REPOSITORY}}:${{env.BUILD_ID}}"
          current_branch=$(git branch --show-current)
          git checkout -b ${{env.HELM_BRANCH}} && git merge ${current_branch}
          git push --force origin ${{env.HELM_BRANCH}}